// <auto-generated />
using System;
using FlashcardApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlashcardApi.Migrations
{
    [DbContext(typeof(FlashcardDbContext))]
    [Migration("20250313014354_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("FlashcardApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "General trivia and facts",
                            Name = "General Knowledge"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Programming concepts and code snippets",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Foreign language vocabulary",
                            Name = "Languages"
                        });
                });

            modelBuilder.Entity("FlashcardApi.Models.Flashcard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("EasinessFactor")
                        .HasColumnType("REAL");

                    b.Property<string>("Hint")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NextReviewAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepetitionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("FlashcardApi.Models.StudySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlashcardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualityOfResponse")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StudiedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlashcardId");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("FlashcardApi.Models.Flashcard", b =>
                {
                    b.HasOne("FlashcardApi.Models.Category", "Category")
                        .WithMany("Flashcards")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FlashcardApi.Models.StudySession", b =>
                {
                    b.HasOne("FlashcardApi.Models.Flashcard", "Flashcard")
                        .WithMany()
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flashcard");
                });

            modelBuilder.Entity("FlashcardApi.Models.Category", b =>
                {
                    b.Navigation("Flashcards");
                });
#pragma warning restore 612, 618
        }
    }
}
